name: Build tests

on: 
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          # fetch full history so refs are available
          fetch-depth: 0
          # on PRs this is the source branch, otherwise the pushed branch
          ref: ${{ github.head_ref || github.ref }}

      - name: Run make
        run: |
          sudo apt-get install checkpolicy
          sudo apt-get install selinux-utils selinux-policy-dev
          make clean
          make enableaudit
          make
          sudo make install
      - name: Generate policy checksum
        run: |
          find /etc/selinux/confident_policy -type f -exec sha256sum {} \; | cut -d' ' -f1 | sort | sha256sum > policy-files.sha256
          
      - name: Create Policy Artifact
        uses: actions/upload-artifact@v4
        with:
          name: confident-sepolicy
          path: /etc/selinux/confident_policy

      - name: Create Directory Checksum Artifact
        uses: actions/upload-artifact@v4
        with:
          name: confident-sepolicy-sha256
          path: policy-files.sha256
